---
- name: Configurazione di Rocky Linux 9
  hosts: all
  become: true

  tasks:
    # Aggiorna tutti i pacchetti
    - name: Aggiorna tutti i pacchetti
      yum:
        name: "*"
        state: latest

    # Installa pacchetti necessari
    - name: Installa pacchetti richiesti
      yum:
        state: present
        with_items:
          - yum-utils
          - device-mapper-persistent-data
          - lvm2
          - python3-pip

    # Installa modulo Python 'requests'
    - name: Installa il modulo Python 'requests'
      pip:
        name: requests
        executable: pip3

    # Aggiungi il repository Docker CE
    - name: Configura il repository Docker CE
      yum_repository:
        name: docker-ce
        description: Docker CE Repository
        baseurl: https://download.docker.com/linux/centos/docker-ce.repo
        gpgcheck: yes
        gpgkey: https://download.docker.com/linux/centos/gpg

    # Installa Docker CE
    - name: Installa Docker CE
      yum:
        state: present
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io

    # Abilita e avvia il servizio Docker
    - name: Abilita e avvia Docker
      systemd:
        name: docker
        enabled: true
        state: started

    # Configura rete Docker
    - name: Configura la rete Docker Jenkins
      docker_network:
        name: jenkins_network
        driver: bridge
        ipam_config:
          - subnet: "172.20.0.0/16"

    # Configura il container Jenkins Master
    - name: Configura il container Jenkins Master
      docker_container:
        name: jenkins_master
        image: jenkins/jenkins:lts
        state: started
        restart_policy: always
        networks:
          - name: jenkins_network
            ipv4_address: 172.20.0.2
        ports:
          - "8080:8080"
          - "50000:50000"

    # Configura il container Jenkins Slave
    - name: Configura il container Jenkins Slave
      docker_container:
        name: jenkins_slave
        image: jenkins/inbound-agent
        state: started
        restart_policy: always
        networks:
          - name: jenkins_network
            ipv4_address: 172.20.0.3
        env:
          JENKINS_URL: http://172.20.0.2:8080
          JENKINS_AGENT_NAME: "jenkins_slave"
          JENKINS_AGENT_WORKDIR: "/home/jenkins"
          JENKINS_SECRET: "{{ jenkins_secret }}"
