---
- name: Configurazione di Rocky Linux 9
  hosts: all
  become: true

  tasks:
    # Aggiorna i pacchetti
    - name: Aggiorna tutti i pacchetti
      yum:
        name: "*"
        state: latest

    # Installa i prerequisiti per Docker CE
    - name: Installa pacchetti necessari
      yum:
        name:
          - yum-utils
          - device-mapper-persistent-data
          - lvm2
          - python3-pip
        state: present

    # Installa la libreria Python 'requests'
    - name: Installa il modulo Python 'requests'
      pip:
        name: requests
        executable: pip3

    # Aggiungi il repository Docker CE
    - name: Aggiungi il repository Docker CE
      command: >
        yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo

    # Installa Docker CE
    - name: Installa Docker CE
      yum:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: present

    # Abilita e avvia il servizio Docker
    - name: Abilita e avvia il servizio Docker
      systemd:
        name: docker
        enabled: true
        state: started

    # Creazione della rete Docker per Jenkins
    - name: Creazione di una rete Docker personalizzata
      docker_network:
        name: jenkins_network
        driver: bridge
        ipam_config:
          - subnet: "172.20.0.0/16"

    # Configurazione del container Jenkins Master
    - name: Esegui il container Jenkins Master
      docker_container:
        name: jenkins_master
        image: jenkins/jenkins:lts
        state: started
        restart_policy: always
        networks:
          - name: jenkins_network
            ipv4_address: 172.20.0.2  # IP statico per il Master
        ports:
          - "8080:8080"
          - "50000:50000"

    # Configurazione del container Jenkins Slave
    - name: Esegui il container Jenkins Slave
      docker_container:
        name: jenkins_slave
        image: jenkins/jnlp-slave
        state: started
        restart_policy: always
        networks:
          - name: jenkins_network
            ipv4_address: 172.20.0.3  # IP statico per lo Slave
        env:
          JENKINS_URL: http://172.20.0.2:8080
          JENKINS_AGENT_NAME: "my-agent"
          JENKINS_SECRET: "my-secret"  # Sostituisci con la chiave segreta del Master
